name: Update Dashboard

on:
  schedule:
    - cron: "0 0 * * *"  # run daily
  workflow_dispatch:       # manual trigger
  push:
    paths:
      - "data/events.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate dashboard
        run: python scripts/generate_dashboard.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Update dashboard [skip ci]" || echo "No changes to commit"
          git push https://$PAT@github.com/bernardo1103/grb_statistics.git HEAD:main
        env:
          PAT: ${{ secrets.PAT }}
